-- Database Client dump 8.0.6
-- Host: 127.0.0.1 Database: public

-- Generated by the database client.
CREATE TABLE loans(
    id SERIAL NOT NULL,
    user_id bigint NOT NULL,
    amount numeric(15,2) DEFAULT 0,
    interest numeric(15,2) DEFAULT 0,
    total_amount numeric(15,2) DEFAULT 0,
    status varchar(20) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX uni_loans_user_id ON loans USING btree ("user_id");