-- Database Client dump 8.0.6
-- Host: 127.0.0.1 Database: public

-- Generated by the database client.
CREATE TABLE loan_requests(
    id SERIAL NOT NULL,
    user_id bigint NOT NULL,
    amount numeric(15,2) DEFAULT 0,
    interest numeric(15,2) DEFAULT 0,
    status varchar(20) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX uni_loan_requests_user_id ON loan_requests USING btree ("user_id");
CREATE UNIQUE INDEX uni_loan_requests_status ON loan_requests USING btree ("status");